#
# Azure DevOps pipeline
#
# Application     : Go App
# Created by      : Muhammed Iqbal
#
#


trigger:
  batch: true
  branches:
    include:
    - master
    - development
  paths:
    #include:
    exclude:
    - azure-pipelines.yml
    - README.md

# Don't run against PRs
pr: none

variables:
#- group: <Variable Group Name>

- name: tag
  value:  $(Build.SourceBranchName)-$(GitShortSha)

# Agent VM image name
- name: vmImageName
  value: 'ubuntu-latest'

- name: containerRegistryServiceConnection
  value: 'Docker Hub'

- name: imageRepository
  value: 'diquzart/go-app'

stages:
- stage: Build
  displayName: Build image

  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImageName: $(vmImageName)

    steps:
    - checkout: self
      clean: true
      displayName: Cleaning local repo

    - script: GitShortSha=`git rev-parse --short HEAD` && echo "##vso[task.setvariable variable=GitShortSha]$GitShortSha"
      displayName: Set the Git Short SHA as an environment variablie

    - task: Docker@2
      displayName: Build Container Image
      inputs:
        containerRegistry: '$(containerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '**/Containerfile'
        tags: '$(tag)'
        
    - task: Docker@2
      displayName: Push Image to Container Registry
      inputs:
        containerRegistry: '$(containerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'

